### ISSUE TITLE
Pypoman with integer variables

### ISSUE THREAD

**Issue by juanvalencialopez** [stephane-caron/pypoman#2]
Hello!

Really nice to find this amazing tool! but Im new at MIP and I want to know if Does this library supports integer variables? and if it does how can i compute then? 

Greetings for this amazing job!
Stay safe!

**Comment by stephane-caron** [comment]
Thank you for your interest! Unfortunately pypoman does not handle integer variables, as both [pycddlib](https://github.com/mcmtroffaes/pycddlib) and Bretl & Lall's algorithm work with continuous variables.

You should take a look at the libraries available from SageMath. For instance, it seems that [PPL can handle polyhedra over \mathbb{Z}](http://doc.sagemath.org/html/en/reference/discrete_geometry/sage/geometry/polyhedron/backend_ppl.html).

Hoping this helps!
