### ISSUE TITLE
Possible to include support for projection of point to onto polytope?

### ISSUE THREAD

**Issue by peekxc** [stephane-caron/pypoman#5]
pypoman has the ability to do polytope projection onto a lower dimensional space, however is there a means of projecting a _point_ onto a given polytope? This is sometimes called the minimum norm point in a polytope problem. 

@stephane-caron I was wondering if this feature would be in the scope of the package and, also, whether you had any intuition/advice on how one might accomplish this? I know that one can reformulate as a convex QP, e.g.

```python
import numpy as np
from qpsolvers import solve_qp
from pypoman import compute_polytope_halfspaces

## The point to project 
x0 = np.array([0.5, 5.2])

## The polygon 
P = np.array([[0, 0], [3,0], [4,5], [2,6], [0,4]])

## Reduction to QP
q = -np.reshape(x0, (2,1)) 
A, b = compute_polytope_halfspaces(P)
y = solve_qp(P=np.eye(2), q=q, G=A, h=b.reshape((len(b), 1)), verbose=True, solver="cvxopt")
print("QP solution: y = {}".format(y))

import matplotlib.pyplot as plt 
plt.gca().set_aspect('equal')
plt.plot(*(np.vstack([x, x[0,:]])).T)
plt.scatter(*x0, c = 'red')
plt.scatter(*y, c = 'green')
plt.arrow(*x0.T, *(y-x0).T, width=0.025)
```

But this requires converting the convex hull to the H-form of the polytope and apparently there exist methods (Philip Wolfe's algorithm, possibly a subcomputation of the GJK algorithm, etc.) to do this using only the V-form, though I've been unable to find a nice implementation

**Comment by stephane-caron** [comment]
Yes, that would be in the scope of this library, unfortunately no, I don't know how to do it better than with a least squares / QP :sweat_smile: 

Thank you for the working code :smiley: I've added a [project_point_to_polytope](https://github.com/stephane-caron/pypoman/blob/9eb821d4a9dadc9754758fafe2aaaf4f9f197d6b/pypoman/projection.py#L227) function and added an example in case other users find it useful. (That's in the `master` branch for now, nut released to PyPI yet.)

Feel free to keep us posted if you find a better solution. If you end up implementing one you are absolutely welcome to open a PR. I'll be happy to help review and merge it to the lib.
