### ISSUE TITLE
pypi package doesn't include project_point_to_polytope

### ISSUE THREAD

**Issue by ryanlovett** [stephane-caron/pypoman#7]
If I install 0.5.4 from pypi, the resulting package does not include `project_point_to_polytope`. If I build from source, also version 0.5.4, the resulting package does have it.

That function was committed in Oct. 2021 and at that time, setup.py's version was at 0.5.4.

Would it be possible to release a new version with that function?

**Comment by stephane-caron** [comment]
Thank you for raising this issue :thumbsup: While at it I added some CI and type annotations to the project, and released v0.6.0 to PyPI. Code in the repository, docs and PyPI should be consistent now.

**Comment by stephane-caron** [comment]
And bumping to v1.0.0 since the package is stable :slightly_smiling_face:

**Comment by ryanlovett** [comment]
Great, thanks @stephane-caron !
